id = "blackfox"
name = "BlackFox Theme"
version = "0.3.0"
schema_version = 1
authors = ["Matěj Černý <https://github.com/matejcerny>"]
description = "🦊 Theme for Zed inspired by Intellij Idea"
repository = "https://github.com/matejcerny/BlackFoxZed"
